{ config, lib, pkgs, inputs, ... }: {
	environment = {
		systemPackages = with pkgs; [
			jq
			lz4
			mpv
			zip
			nil
			tree
			gimp
			btop
			wget
			cava
			unzip
			pipes
			wtype
			kitty
			krita
			loupe
			whatsie
			spotify
			udiskie
			blender
			blueman
			mdwatch
			pyright
			harper
			cpufetch
			usbutils
			nautilus
			nwg-look
			opencode
			inkscape
			adw-gtk3
			cliphist
			obsidian
			pciutils
			gammastep
			python315
			fastfetch
			unimatrix
			libnotify
			playerctl
			alsa-utils
			lm_sensors
			pixelorama
			theclicker
			pavucontrol
			gnome-boxes
			clang-tools
			wl-clipboard
			brightnessctl
			xdg-user-dirs
			bibata-cursors
			gnome-calculator
			libsForQt5.qt5ct
			mpvScripts.mpris
			telegram-desktop
			qt6.qtdeclarative
			kdePackages.qt6ct
			kdePackages.kamoso
			xwayland-satellite
			gnome-disk-utility
			gpu-screen-recorder
			kdePackages.kdenlive
			bash-language-server
			(
				discord.override {
      					withVencord = true;
    				}
			)
      			inputs.zen-browser.packages.${pkgs.stdenv.hostPlatform.system}.default
		];
	};
}
