{ pkgs, inputs, ... }: {
	environment = {
		systemPackages = with pkgs; [
			jq
			lz4
			mpv
			zip
			nil
			tree
			btop
			gimp
			wget
			cava
			codex
			unzip
			pipes
			wtype
			krita
			loupe
			nodejs
			harper
			ddcutil
			whatsie
			spotify
			udiskie
			blender
			blueman
			mdwatch
			pyright
			cpufetch
			usbutils
			nautilus
			nwg-look
			inkscape
			adw-gtk3
			cliphist
			obsidian
			pciutils
			gammastep
			python315
			unimatrix
			libnotify
			playerctl
			fastfetch
			hyprpicker
			pixelorama
			theclicker
			pavucontrol
			gnome-boxes
			clang-tools
			libreoffice
			wl-clipboard
			gnome-clocks
			qt5.qtwayland
			qt6.qtwayland
			brightnessctl
			xdg-user-dirs
			gnome-calculator
			libsForQt5.qt5ct
			mpvScripts.mpris
			telegram-desktop
			qt6.qtdeclarative
			kdePackages.qt6ct
			kdePackages.kamoso
			gnome-disk-utility
			xwayland-satellite
			papirus-icon-theme
			zsh-autosuggestions
			kdePackages.kdenlive
			bash-language-server
			zsh-history-substring-search
			inputs.pyroclear.packages.${pkgs.stdenv.hostPlatform.system}.default
      		inputs.zen-browser.packages.${pkgs.stdenv.hostPlatform.system}.default
			inputs.Bibata-Modern-Catppuccin-Mocha-Blue.packages.${pkgs.stdenv.hostPlatform.system}.default
		];
	};
}
